<a href="https://colab.research.google.com/github/hasun/pyStat/blob/master/PyStat_2_2_%EA%B8%B0%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [13]:
np.arange(start=1,stop=6,step=1)

array([1, 2, 3, 4, 5])

In [14]:
np.tile ("A",5)

array(['A', 'A', 'A', 'A', 'A'], dtype='<U1')

In [15]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
d1_array = np.array([1,2,3,4,5])
d1_array

array([1, 2, 3, 4, 5])

In [18]:
d1_array[1:3]

array([2, 3])

In [19]:
d2_array = np.array ([[1,2,3,4,5],[6,7,8,9,10]])

In [20]:
d2_array[1, 2:4]

array([8, 9])

In [21]:
import pandas as pd

In [22]:
sample_array = {1,2,3,4,5}
sample_df = pd.DataFrame ({'col1' : d1_array,
                           'col2' : d1_array*2,
                           'col3' : ["A","B","C","D","E"]
                           })
print (sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [9]:
file_data = pd.read_csv("/content/sample_data/california_housing_train.csv")
print (file_data)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  media

In [23]:
df_1 = pd.DataFrame({'col1': np.array([1,2,3]),'col2': np.array(['A','B','C'])})
df_2 = pd.DataFrame({'col1': np.array([4,5,6]),'col2': np.array(['D','E','F'])})

print (pd.concat([df_1,df_2]))
print (pd.concat([df_1,df_2], axis=1))

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F
   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F


In [26]:
print (sample_df.col2)
print (sample_df["col2"])
print (sample_df[["col2","col3"]])
print (sample_df.drop ("col1", axis=1))

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64
0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64
   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E
   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E


In [31]:
print (sample_df.head(n=3))
print (sample_df.query('index==0'))
print (sample_df.query('col3=="A"'))
print (sample_df.query('col3=="A" | col3== "D"'))
print (sample_df.query('col3=="A"')[["col2","col3"]])

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
   col1  col2 col3
0     1     2    A
   col1  col2 col3
0     1     2    A
   col1  col2 col3
0     1     2    A
3     4     8    D
   col2 col3
0     2    A


In [34]:
type(sample_df.col1)
type(np.array(sample_df.col1))
type(sample_df.col1.values)

numpy.ndarray