<a href="https://colab.research.google.com/github/hasun/pyStat/blob/master/PyStat_2_2_%EA%B8%B0%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [5]:
np.arange(start=1,stop=6,step=1)

array([1, 2, 3, 4, 5])

In [6]:
np.tile ("A",5)

array(['A', 'A', 'A', 'A', 'A'], dtype='<U1')

In [7]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [10]:
d1_array = np.array([1,2,3,4,5])
d1_array

array([1, 2, 3, 4, 5])

In [11]:
d1_array[1:3]

array([2, 3])

In [12]:
d2_array = np.array ([[1,2,3,4,5],[6,7,8,9,10]])

In [13]:
d2_array[1, 2:4]

array([8, 9])

In [14]:
import pandas as pd

In [20]:
sample_array = {1,2,3,4,5}
sample_df = pd.DataFrame ({'col1' : d1_array,
                           'col2' : d1_array*2,
                           'col3' : ["A","B","C","D","E"]
                           })
print (sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E
